# Generated by Django 6.0.1 on 2026-01-19 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('functie', models.CharField(choices=[('Barista', 'Barista'), ('Casier', 'Casier'), ('Administrator', 'Administrator'), ('Director', 'Director')], max_length=100)),
                ('salariu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('data_angajarii', models.DateField(default=django.utils.timezone.now)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('este_angajat', models.BooleanField(default=True, help_text='Bifat in cazul in care angajatul este activ, debifat in cazul in care angajatul a demisionat')),
            ],
            options={
                'verbose_name_plural': 'Angajati',
            },
        ),
    ]
