# Generated by Django 6.0.1 on 2026-01-19 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(choices=[('Cafele', [('Espresso', 'Espresso'), ('Espresso Lung', 'Espresso Lung'), ('Americano', 'Americano'), ('Cappuccino', 'Cappuccino'), ('Caffe Latte', 'Caffe Latte'), ('Flat White', 'Flat White')]), ('Bauturi Calde', [('Ciocolata Calda', 'Ciocolata Calda'), ('Chai Latte', 'Chai Latte'), ('Ceai', 'Ceai')]), ('Bauturi Reci', [('Iced Coffee', 'Iced Coffee'), ('Smoothie', 'Smoothie'), ('Frappe', 'Frappe'), ('Milkshake', 'Milkshake')]), ('Soft Drinks', [('Coca-Cola', 'Coca-Cola'), ('Pepsi', 'Pepsi'), ('Apa plata', 'Apa plata'), ('Apa minerala', 'Apa minerala')]), ('Dulciuri', [('Negresa', 'Negresa'), ('Fursec American', 'Fursec American'), ('Tiramisu', 'Tiramisu'), ('Cheesecake', 'Cheesecake'), ('Briosa', 'Briosa')])], max_length=100)),
                ('pret_vanzare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_achizitie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantitate', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='cafenea.categorie')),
            ],
        ),
    ]
