# Generated by Django 6.0.1 on 2026-01-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0003_alter_produs_categorie_alter_produs_cost_achizitie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('gen', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Nespecificat', 'Nespecificat')], max_length=20)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('data_inregistrarii', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterField(
            model_name='produs',
            name='denumire',
            field=models.CharField(choices=[('Cafele', [('Espresso', 'Espresso'), ('Espresso Lung', 'Espresso Lung'), ('Espresso Decaf', 'Espresso Decaf'), ('Espresso Machiatto', 'Espresso Machiatto'), ('Espresso Con Panna', 'Espresso Con Panna'), ('Americano', 'Americano'), ('Cappuccino', 'Cappuccino'), ('Caffe Latte', 'Caffe Latte'), ('Flat White', 'Flat White')]), ('Bauturi Calde', [('Ciocolata calda', 'Ciocolata calda'), ('Chai latte', 'Chai latte'), ('Ceai', 'Ceai')]), ('Bauturi Reci', [('Iced Coffee', 'Iced Coffee'), ('Greek Frappe', 'Greek Frappe'), ('Ness Frappe', 'Ness Frappe'), ('Espresso Tonic', 'Espresso Tonic'), ('Milkshake', 'Milkshake'), ('Smoothie', 'Smoothie')]), ('Soft Drinks', [('Coca-Cola', 'Coca-Cola'), ('Fanta', 'Fanta'), ('Sprite', 'Sprite'), ('Pepsi', 'Pepsi'), ('Apa Plata', 'Apa Plata'), ('Apa Minerala', 'Apa Minerala'), ('RedBull', 'RedBull')]), ('Dulciuri', [('Negresa', 'Negresa'), ('Fursec American', 'Fursec American'), ('Briosa', 'Briosa'), ('Biscuite cu ovaz', 'Biscuite cu ovaz'), ('Mini Croissant', 'Mini Croissant'), ('Biscuiti Vegani', 'Biscuiti Vegani'), ('Salam de Biscuiti', 'Salam de Biscuiti'), ('Ciocolata de Casa', 'Ciocolata de Casa')])], max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='bautura_preferata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fani', to='cafenea.produs'),
        ),
    ]
