# Generated by Django 6.0.1 on 2026-01-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0004_client_delete_categorie_alter_produs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bautura_preferata',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('categorie', 'Dulciuri'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fani', to='cafenea.produs'),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comenzii', models.DateTimeField(auto_now_add=True)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comenzi_procesate', to='cafenea.angajat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comenzi', to='cafenea.client')),
            ],
            options={
                'verbose_name_plural': 'Comenzi',
            },
        ),
        migrations.CreateModel(
            name='ElementComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente', to='cafenea.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafenea.produs')),
            ],
        ),
    ]
