# Generated by Django 6.0.1 on 2026-01-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0005_alter_client_bautura_preferata_comanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('continut', models.TextField(verbose_name='Descriere eveniment/noutate')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='noutati/')),
                ('data_eveniment', models.DateField(blank=True, null=True)),
                ('este_activa', models.BooleanField(default=True)),
                ('creat_la', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stiri',
                'ordering': ['-creat_la'],
            },
        ),
    ]
