# Generated by Django 6.0.1 on 2026-01-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0006_stire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subiect', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('data_trimiterii', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mesaje Contact',
                'ordering': ['-data_trimiterii'],
            },
        ),
    ]
