# Generated by Django 6.0.1 on 2026-01-19 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafenea', '0007_mesajcontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='gen',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Nespecificat', 'Nespecificat')], default='Nespecificat', max_length=20),
        ),
    ]
